name: doge
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pybind11
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - opencv-python
    - numpy==1.26.4
    - ffmpeg==4.4.2
    - mujoco
    - scipy
    - torch
    - gymnasium[all]
    - absl-py
    - apache-beam
    - asttokens
    - astunparse
    - attrs
    - avro-python3
    - backcall
    - cachetools
    - certifi
    - charset-normalizer
    - clang
    - crcmod
    - cycler
    - decorator
    - dill
    - docopt
    - executing
    - fastavro
    - flatbuffers
    - fonttools
    - future
    - gast
    - gin-config
    - google-api-core
    - google-auth
    - google-auth-oauthlib
    - google-cloud-bigquery-storage
    - google-pasta
    - googleapis-common-protos
    - grpcio
    - h5py
    - hdfs
    - httplib2
    - idna
    - imageio
    - importlib-metadata
    - ipython
    - jedi
    - keras
    - Keras-Preprocessing
    - kiwisolver
    - Markdown
    - matplotlib
    - matplotlib-inline
    - mediapy
    - natsort
    - networkx
    - numpy
    - oauth2client
    - oauthlib
    - opencv-python
    - opt-einsum
    - orjson
    - packaging
    - parameterized
    - parso
    - pexpect
    - pickleshare
    - Pillow
    - promise
    - prompt-toolkit
    - protobuf
    - ptyprocess
    - pure-eval
    - pyarrow
    - pyasn1
    - pyasn1-modules
    - pydot
    - Pygments
    - pymongo
    - pyparsing
    - python-dateutil
    - pytz
    - PyWavelets
    - requests
    - requests-oauthlib
    - rsa
    - scikit-image
    - scikit-video
    - scipy
    - six
    - stack-data
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow
    - tensorflow-addons
    - tensorflow-datasets
    - tensorflow-estimator
    - tensorflow-metadata
    - termcolor
    - tifffile
    - tqdm
    - traitlets
    - typeguard
    - typing-extensions
    - urllib3
    - wcwidth
    - Werkzeug
    - wrapt
    - zipp
    - chex
    - einops
    - jax[cuda]
    - jaxlib
    - optax
    - tensorflow_probability
    - pandas
    - loris
    - build
    - patchelf
    - cloudpickle
    - colored
    - gputil
    - msgpack
    - psutil
    - ruamel.yaml
    - tensorflow-cpu
    - zmq
    - dm_control
    - gym
